### ISSUE TITLE
Error when artist name is less than 2 characters

### ISSUE THREAD

**Issue by Mudkip2345** [T0biasCZe/Windows-Media-Player-Discord-RPC#17]
![RPC1](https://github.com/user-attachments/assets/3e6bbb7f-141f-498d-b77c-8c5d3c11d965)

Here, it works normally

![RPC2](https://github.com/user-attachments/assets/c8a9112f-e3e0-4554-a71d-79fef5d2d51b)

In this image, the artist is the band '3', and as such throws this error.

**Comment by T0biasCZe** [comment]
Should be fixed https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/releases/tag/v2.2.4

also what WMP Skin is that?

**Comment by Mudkip2345** [comment]
It's WMP11, Vista's Windows Media Player. There's a program you can use to swap WMP12 for WMP 11 on Windows 7. ( I think it would work for 10? I have not tried it.) 
It's included as part of this pack: https://mega.nz/file/ihUCEa7A#5Sb6fDaQNCT1d8Ccm3ikgwjJ6KoGPmm7f8re0tRMt18

**Comment by Mudkip2345** [comment]
![image](https://github.com/user-attachments/assets/b53d8047-ce0f-4f4c-89ce-98d4f7639137)
It appears to still throw the error

**Comment by T0biasCZe** [comment]
Fixed 2: https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/releases/tag/v2.2.4

i padded the short name with space and discord didnt like that

**Comment by Mudkip2345** [comment]
![image](https://github.com/user-attachments/assets/982bc1cb-27ad-4361-9ea9-c9d13516ff45)
Works great, thanks!
